version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: anigo-backend-prod
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=anigo
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - anigo-network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: anigo-db-prod
    environment:
      POSTGRES_DB: anigo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - anigo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: anigo-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - anigo-network
    restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  anigo-network:
    driver: bridge

